### ISSUE TITLE
'str' object has no attribute '_sa_instance_state'

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#284]
looks harmless, but what is this?

```
Traceback (most recent call last):
  File "/home/.../editor.py", line 1619, in idle_callback
    on_select(text)  # `on_select` will know how to convert the
  File "/home/.../accession.py", line 1261, in on_sp_select
    self.set_model_attr('species', value)
  File "/home/.../accession.py", line 1378, in set_model_attr
    setattr(self.model, attr, value)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/attributes.py", line 224, in __set__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/attributes.py", line 802, in set
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/attributes.py", line 824, in fire_replace_event
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 85, in set_
AttributeError: 'str' object has no attribute '_sa_instance_state'
```

**Comment by mfrasca** [comment]
I can write a few lines that transform the string to a valid Species value, but this code belongs to the class, not to the client function, and we have no such function in `Species`.
retrieve species given its string representation, the opposite of the `str` method.

**Comment by mfrasca** [comment]
closing dangling issues.
