### ISSUE TITLE
review and complete 3.1

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#382]
some parts of the user interface for 3.1 do not work properly:
- [ ] select search from drop-down should execute the search
- [ ] add Notes interface for Location
- [ ] we want some margin next to the ghini icon in the home screen
- [ ] Accession should show taxon identification with qualifier
- [ ] Accession 2014.0668 in cuchubo does not show infobox
- [ ] Plant: adding a new note results in hardly visible video in plant 2014.0028
- [ ] Accession: wild status does not get sensitive
- [ ] Location, Container, Germination media are not selectable in Propagation Editor
- [ ] Species: can not add infraspecific parts
- [ ] Species always asks 'confirm lose changes' even after no change at all.

**Comment by mfrasca** [comment]
the ones still open do not stand so much in the way, so I published 3.1.3 to the 3.1 line.

**Comment by mfrasca** [comment]
> select search from drop-down should execute the search

I had done something to implement this one, but it totally broke the whole interface.
28624fbc547031b03ff96cdfe8eb4127d496d57c

**Comment by mfrasca** [comment]
published 3.1.5

**Comment by mfrasca** [comment]
while installing 3.1 on mint Sonya (18.2), I met this:
```
Traceback (most recent call last):
  File "/home/loes/.virtualenvs/ghide/lib/python3.5/site-packages/bauble/plugins/garden/institution.py", line 444, in on_select_map_clicked
    map = MapViewer(_('Zoom to garden'), self.view.get_window())
  File "/home/loes/.virtualenvs/ghide/lib/python3.5/site-packages/bauble/plugins/garden/institution.py", line 64, in __init__
    self.clutter_view.set_horizontal_wrap(True)
AttributeError: 'View' object has no attribute 'set_horizontal_wrap'
```

**Comment by mfrasca** [comment]
@cwyse , do you think you want to add to this "epic"? what else is there to review in the current ghini-3.1-dev? 
about names for versions: the major one, it's for advertisement, not really meaningful. let's say it's 3 because of GTK3.
the minor one is for the database version. if it's compatible with ghini-1.1, then it's 3.1.
a version like 4.0 would indicate database compatibility with 1.0 and 3.0; why major 4, you may say.
