### ISSUE TITLE
adapt code and tests to windows

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#384]
after #109 and #379 we placed [our tests on appveyor](https://ci.appveyor.com/project/mfrasca/ghini-desktop), and that's testing on Windows.  obviously they don't work just out of the box, and luckily _most_ differences are in the testing code, not in the code being tested.  _Some_ are in the distributed program.
anyhow, we need to make sure that tests run and succeed.

**Comment by mfrasca** [comment]
```
ERROR: test_get_next_code_previous_year_subst (bauble.plugins.garden.test.AccessionGetNextCode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\ghini-desktop\bauble\plugins\garden\test.py", line 2331, in test_get_next_code_previous_year_subst
    self.assertEquals(Accession.get_next_code(u'%{Y-1}.####')[5:], '0013')
  File "C:\projects\ghini-desktop\bauble\plugins\garden\accession.py", line 668, in get_next_code
    format = today.strftime(format)
ValueError: Invalid format string
```
